=== MyMagisterOrganization/JavaApplicationXML/src/XML/Students.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Students.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE students SYSTEM "Students.dtd">

    <students>
    ...
    </students>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT students (student|digest)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT digest (date)*>
<!ATTLIST digest
    kk CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT date (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT student (addr|sname|name|fname)*>
<!ATTLIST student
    pin CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT fname (#PCDATA)>
<!--- Put your DTDDoc comment here. -->
<!ELEMENT sname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT addr (home|city)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT city (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT home (#PCDATA)>
<!ATTLIST home
    num CDATA #IMPLIED
  >

=== MyMagisterOrganization/JavaApplicationXML/src/XML/Students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->



<?xml-stylesheet type="text/xsl" href="studentXSL.xsl" ?>
 <!DOCTYPE students SYSTEM "Students.dtd">
<!--
    Document   : StudentXMLDocument.xml
    Created on : 27 November 2009, 20:38
    Author     : Administrator
    Description:
        Purpose of the document follows.
-->

<students>
    <digest kk="kkkk">
            <date>12121</date>
            <date>333333333</date>
            <date> 44444</date>
    </digest>
    <student pin ="11111">
        <name>zzz</name>
        <sname>bbb</sname>
        <addr>
            <city> tttt </city>
            <home num="111" >
                hhhhhhh
            </home>
        </addr>
    </student>
    <student pin ="2222">
        <name>zzz11</name>
        <sname>bbb111</sname>
        <addr>
            <city> tttt111 </city>
            <home num="222" >
                hhhhhhh111
            </home>
        </addr>
    </student>
    <student pin ="3333">
        <name>zzz333</name>
        <sname>bbb3333</sname>
        <addr>
            <city> tttt333 </city>
            <home num="33333" >
                hhhhhhh3333
            </home>
        </addr>
    </student>
    <student pin ="11111">
        <fname>zzz</fname>
        <sname>bbb</sname>
        <addr>
            <city> tttt </city>
            <home num="111" >
                hhhhhhh
            </home>
        </addr>
    </student>
</students>
